### ISSUE TITLE
Error when using diff and diff-input options

### ISSUE THREAD

**Issue by berkayyildiz** [FranciscoKnebel/ngx-translate-check#6]
I was trying the project and I couldn't use. files option work without any problem but other options give errors

```
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at /usr/local/lib/node_modules/ngx-translate-check/bin/ngx-translate-check:24:30467
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:52:12)
```

```
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at /usr/local/lib/node_modules/ngx-translate-check/bin/ngx-translate-check:24:29619
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:52:12)
```

**Comment by FranciscoKnebel** [comment]
Hello @berkayyildiz, thank you for giving the package a try.

1. Can you submit a sample of your output JSON, so I can reproduce the error?
2. The file you use with the `diff` command is the one you generate using the `files` command.

**Comment by berkayyildiz** [comment]
Sorry, there was no problem, I didn't quite understand that the diff command consumes the output of files command. It worked fine when I did it that way, thanks.

**Comment by berkayyildiz** [comment]
By the way I was looking for solutions for the same problem and I ended up with write a vscode extension myself that highlight the differences, may be it can be useful for you too you can check here https://github.com/Berkaylar/Find-Missing-Keys.
